### PR TITLE
docs: adding individual blocks for each team member to write smth

### PR DESCRIPTION
**Pull request by spirovskib**
I have added heading2 level titles to the bottom of the Readme file for each member of the team to write something using pull request.

### CODE REVIEW

**Review by magicalturtle420 — APPROVED** [review]
LGTM :)

**Comment by magicalturtle420** [comment]
Very nice code!

**Review by magicalturtle420 — APPROVED** [review]
LGTM 2

**Review by simeonovski — APPROVED** [review]
Looks good!

**Review by simeonovski — APPROVED** [review]
Looks good.

**Review by Geca13 — APPROVED** [review]
LGTM

**Pull request merged**
